
# Server
server.port=8081

# MySQL =
spring.datasource.url=jdbc:mysql://localhost:3306/hrplatform?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=YOUR_DB_PASSWORD_HERE
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA ? create-drop creates tables fresh every run (good for now)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT secret ? keep this long and secret
jwt.secret=YOUR_JWT_SECRET_HERE
jwt.expiration.ms=86400000
spring.jpa.open-in-view=false
logging.level.org.springframework.security=TRACE
# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=prerna.rajora2424@gmail.com
spring.mail.password=YOUR_APP_PASSWORD_HERE
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true